[project]
name = "occ_coder"
description = "An app used for occupation coding"
authors = [{name = "National Institute of Statistics of Rwanda", email = "info@statistics.gov.rw"}]
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "dotenv",
    "pandas",
    "numpy",
    "openai==0.28",
    "Path",
    "re",
    "dash",
    "ast"
    "ragas",
]

[project.urls]
homepage = "need to change"

[tool.setuptools.dynamic]
version = {attr = "occ_coder.__version__"}

[tool.setuptools.packages.find]
include = ["occ_coder"]
namespaces = false